apiVersion: v1
kind: Secret
metadata:
  namespace: ns2
  name: bar
stringData:
  # printf FOO | base64
  foo: ref+awsssm://foo/bar/data/baz?mode=singleparam&version=1#/ns2/bar/foo
  # printf BAR | base64
  bar: ref+awsssm://foo/bar/data/baz?mode=singleparam&version=1#/ns2/bar/bar
