project_name: flux-repo
builds:
  - id: flux-repo
    main: ./cmd/main
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X github.com/mumoshu/flux-repo/Version={{.Version}}
changelog:
  filters:
    # commit messages matching the regexp listed here will be removed from
    # the changelog
    # Default is empty
    exclude:
      - '^docs:'
      - typo
dockers:
  - goos: linux
    goarch: amd64
    goarm: ''
    binaries:
      - flux-repo
    builds:
      - flux-repo
    image_templates:
      - "mumoshu/flux-repo:latest"
      - "mumoshu/flux-repo:{{ .Tag }}"
      - "mumoshu/flux-repo:{{ .Tag }}-{{ .Env.FLUX_VERSION }}"
      - "mumoshu/flux-repo:v{{ .Major }}"
    build_flag_templates:
      - "--pull"
      - "--build-arg=FLUX_VERSION={{.Env.FLUX_VERSION}}"
