apiVersion: v1
kind: Secret
metadata:
  namespace: ns2
  name: bar
stringData:
  # printf FOO | base64
  foo: ref+awssecrets://foo/bar?version_id=B0FA5329-CD35-489E-A013-F3639346ACB0#/ns2/bar/foo
  # printf BAR | base64
  bar: ref+awssecrets://foo/bar?version_id=B0FA5329-CD35-489E-A013-F3639346ACB0#/ns2/bar/bar
