apiVersion: v1
kind: Secret
metadata:
  namespace: ns1
  name: foo
stringData:
  # printf FOO | base64
  foo: ref+s3://fluxrepotest/bar/data/baz?version=3yYji9YJgwgOMjGFlJR7JK338IMl9DFE#/ns1/foo/foo
  # printf BAR | base64
  bar: ref+s3://fluxrepotest/bar/data/baz?version=3yYji9YJgwgOMjGFlJR7JK338IMl9DFE#/ns1/foo/bar
