apiVersion: v1
kind: Secret
metadata:
  namespace: ns2
  name: bar
stringData:
  # printf FOO | base64
  foo: ref+s3://fluxrepotest/bar/data/baz?version=3yYji9YJgwgOMjGFlJR7JK338IMl9DFE#/ns2/bar/foo
  # printf BAR | base64
  bar: ref+s3://fluxrepotest/bar/data/baz?version=3yYji9YJgwgOMjGFlJR7JK338IMl9DFE#/ns2/bar/bar
