apiVersion: v1
kind: Secret
metadata:
  namespace: ns2
  name: bar
stringData:
  # printf FOO | base64
  foo: ref+vault://foo/bar/data/baz?version=13#/ns2/bar/foo
  # printf BAR | base64
  bar: ref+vault://foo/bar/data/baz?version=13#/ns2/bar/bar
